order_heading_first: ROB@WORK 3
order_heading_second: Order Objects by drag and drop them from the upper boxes to the lower
order_wait: Please wait, Robot will deliver your Order
move_heading_first: ROB@WORK 3
move_heading_second: Press the Button to move the manipulator
move_wait: Please wait, arm is in motion
move_button: Moveit Demo
